[project]
name = "bingx-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.12",
    "python-decouple>=3.8",
    "python-dotenv>=1.0.1",
]
